In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
arr=np.array([4,5,6])

In [4]:
print(arr)

[4 5 6]


In [5]:
arr2=np.array([[5,6,7],[8,9,4],[2,7,8]])

In [6]:
arr2

array([[5, 6, 7],
       [8, 9, 4],
       [2, 7, 8]])

In [7]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [10]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [11]:
arr3=np.arange(1,10,2)

In [12]:
arr3

array([1, 3, 5, 7, 9])

In [18]:
# yadi hame 100 to 300 ko 9 part me devide karna hai to linspace ka use karenge and 300 hundred ko bhi print kar dega

In [19]:
arr4=np.linspace(100,300,9)

In [20]:
arr4

array([100., 125., 150., 175., 200., 225., 250., 275., 300.])

In [21]:
arr5=np.linspace(1,2,6)

In [22]:
arr5

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [23]:
arr6=np.full((5,5),10)

In [24]:
arr6

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [25]:
arr7=np.full((6,7),9)

In [26]:
arr7

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [28]:
# EXPLORING NUMPY ARRAY (SHAPE,RESHAPE,NDIM,SIZE ETC)

In [29]:
arr8=np.array([[7,8,9],[10,56,78]])

In [30]:
arr8

array([[ 7,  8,  9],
       [10, 56, 78]])

In [32]:
arr8.shape

(2, 3)

In [35]:
arr9=np.array([[7,8,9],[10,56,78],[8,5,3]])

In [36]:
arr9.shape

(3, 3)

In [37]:
arr10=np.array([[7,8,9],[10,56,78]])

In [38]:
arr10.shape=(3,2)

In [39]:
arr10

array([[ 7,  8],
       [ 9, 10],
       [56, 78]])

In [40]:
arr10.shape

(3, 2)

In [42]:
arr11=arr10.reshape(2,1,3)

In [43]:
arr11

array([[[ 7,  8,  9]],

       [[10, 56, 78]]])

In [44]:
arr11.shape

(2, 1, 3)

In [48]:
arr11.ndim

3

In [47]:
# number of elements in array
arr11.size

6

In [1]:
import numpy as np

In [4]:
# 1 TO 100 TAK KE NUMBER KO RANDOMLY 12 PART ME DEVIDE KARKE PRINT KARA SAKTE HAI

In [5]:
arr=np.random.randint(1,100,12)

In [6]:
arr

array([68, 93, 13,  9, 84, 34, 86,  3, 89, 65, 73, 79])

In [7]:
arr.shape

(12,)

In [8]:
arr=arr.reshape(6,2)

In [9]:
arr

array([[68, 93],
       [13,  9],
       [84, 34],
       [86,  3],
       [89, 65],
       [73, 79]])

In [10]:
arr=arr.reshape(12)

In [11]:
arr

array([68, 93, 13,  9, 84, 34, 86,  3, 89, 65, 73, 79])

In [12]:
# MATHEMATICAL OPERATIONS USING NUMPY

In [18]:
# array comprision true and false

In [14]:
import numpy as np

In [28]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,3])
arr3=np.array([1,2,3])

In [29]:
np.equal(arr1,arr2,arr3)

array([0, 0, 1])

In [30]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,3])
arr3=np.array([1,2,3])

In [31]:
np.equal(arr1,arr3)

array([ True,  True,  True])

In [34]:
arr1=np.array([1,2,3])
arr2=np.array([5,6,3])
arr3=np.array([1,2,3])

In [36]:
np.array_equal(arr1,arr2)

False

In [37]:
np.array_equal(arr1,arr3)

True

In [38]:
arr1

array([1, 2, 3])

In [39]:
arr2

array([5, 6, 3])

In [40]:
arr3

array([1, 2, 3])

In [41]:
np.sum(arr1)

6

In [42]:
np.sum(arr2)

14

In [43]:
np.sum(arr3)

6

In [44]:
np.sum([[1,2],[8,9]])

20

In [47]:
np.sum([[1,2],[8,9]],axis=0) # column wise sum

array([ 9, 11])

In [48]:
np.sum([[1,2],[8,9]],axis=1) # row wise sum

array([ 3, 17])

In [49]:
# np.sum(),np.subtract(),np.multiply(),np.divide()

In [51]:
arr1

array([1, 2, 3])

In [52]:
arr2

array([5, 6, 3])

In [53]:
np.subtract(arr1,arr2)

array([-4, -4,  0])

In [54]:
np.multiply(arr1,arr2)

array([ 5, 12,  9])

In [55]:
np.divide(arr1,arr2)

array([0.2       , 0.33333333, 1.        ])

In [56]:
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

In [57]:
# sin(),cos(),exp(),log(),sqrt()

In [58]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081])

In [59]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

In [60]:
arr2

array([5, 6, 3])

In [61]:
np.mean(arr2)

4.666666666666667

In [62]:
np.std(arr2)

1.247219128924647

In [64]:
np.var(arr2)

1.5555555555555554

In [65]:
np.median(arr2)

5.0

In [66]:
np.max(arr2)

6

In [67]:
np.min(arr2)

3

In [68]:
arr1

array([1, 2, 3])

In [69]:
arr2

array([5, 6, 3])

In [70]:
arr1+arr2

array([6, 8, 6])

In [71]:
a=np.array([[3,4,5],[6,7,8],[1,2,3]])
b=np.array([1,2,3])

In [72]:
a+b

array([[ 4,  6,  8],
       [ 7,  9, 11],
       [ 2,  4,  6]])

In [1]:
# indexing and slicing

In [2]:
import numpy as np

In [3]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([[10,20,30],[40,50,60]])

In [4]:
arr1

array([10, 20, 30, 40, 50])

In [5]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [6]:
arr1[2]

30

In [7]:
arr1[-3]

30

In [8]:
arr1[-1]

50

In [9]:
arr1[1:4]

array([20, 30, 40])

In [10]:
arr1[:]

array([10, 20, 30, 40, 50])

In [11]:
arr1[1:]

array([20, 30, 40, 50])

In [14]:
arr1[-2:]

array([40, 50])

In [16]:
arr1[-1:]

array([50])

In [18]:
arr1[-5:]

array([10, 20, 30, 40, 50])

In [19]:
arr2

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
arr2[1][2]

60

In [21]:
arr2[1][1]

50

In [22]:
arr2[0][1]

20

In [23]:
arr2[0][1:]

array([20, 30])

In [25]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr3.shape

(3, 3)

In [28]:
arr3[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [31]:
arr3[1:,1:]   # esme 1st row and 1st column ko read karega

array([[5, 6],
       [8, 9]])

In [32]:
arr3[0:,2:]

array([[3],
       [6],
       [9]])

In [33]:
arr3[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [34]:
arr3[0:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [35]:
arr3[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [37]:
    import numpy as np               

In [38]:
a1=np.array([[2,3],[8,9]])
a2=np.array([[5,6]])

In [39]:
a1

array([[2, 3],
       [8, 9]])

In [40]:
a2

array([[5, 6]])

In [47]:
np.concatenate((a1,a2),axis=0)  # row wise concatenate

array([[2, 3],
       [8, 9],
       [5, 6]])

In [48]:
np.concatenate((a1,a2))

array([[2, 3],
       [8, 9],
       [5, 6]])

In [49]:
np.concatenate((a1,a2.T),axis=1)   # column wise concatenate

array([[2, 3, 5],
       [8, 9, 6]])

In [51]:
b1=np.array([5,6,7])
b2=np.array([8,4,2])      # one diamension array hai to dono (stack)join hokar two diamension ban jayega
np.stack((b1,b2))

array([[5, 6, 7],
       [8, 4, 2]])

In [54]:
np.stack((b1,b2),axis=0)    # axis=0,row wise join

array([[5, 6, 7],
       [8, 4, 2]])

In [55]:
np.stack((b1,b2),axis=1)    # axis=1,column wise join

array([[5, 8],
       [6, 4],
       [7, 2]])

In [56]:
np.vstack((b1,b2))

array([[5, 6, 7],
       [8, 4, 2]])

In [57]:
np.hstack((b1,b2))

array([5, 6, 7, 8, 4, 2])

In [58]:
c1=np.array([[6],[8],[9]])
c2=np.array([[4],[2],[3]])
np.vstack((c1,c2))

array([[6],
       [8],
       [9],
       [4],
       [2],
       [3]])

In [59]:
c1=np.array([[6],[8],[9]])
c2=np.array([[4],[2],[3]])
np.hstack((c1,c2))

array([[6, 4],
       [8, 2],
       [9, 3]])

In [60]:
c1

array([[6],
       [8],
       [9]])

In [61]:
c2

array([[4],
       [2],
       [3]])

In [62]:
np.column_stack((c1,c2))

array([[6, 4],
       [8, 2],
       [9, 3]])

In [63]:
np.row_stack((c1,c2))

array([[6],
       [8],
       [9],
       [4],
       [2],
       [3]])

In [1]:
import numpy as np

In [3]:
a1=np.arange(20)

In [4]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.split(a1,5)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10, 11]),
 array([12, 13, 14, 15]),
 array([16, 17, 18, 19])]

In [6]:
np.split(a1,2)

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [8]:
np.split(a1,[2,5,7])  # pahle 2 element ka fir 3 element ka fir 2 element ka fir jo bach jayega uska array bana dega

[array([0, 1]),
 array([2, 3, 4]),
 array([5, 6]),
 array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [10]:
np.array_split(a1,6)

[array([0, 1, 2, 3]),
 array([4, 5, 6, 7]),
 array([ 8,  9, 10]),
 array([11, 12, 13]),
 array([14, 15, 16]),
 array([17, 18, 19])]

In [11]:
a2=np.array([[2,3,4,5],[5,6,7,8],[1,5,4,8],[9,2,5,8]])

In [12]:
a2

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [1, 5, 4, 8],
       [9, 2, 5, 8]])

In [14]:
np.hsplit(a2,2)  # column wise 2 part me horizontal split kar dega

[array([[2, 3],
        [5, 6],
        [1, 5],
        [9, 2]]),
 array([[4, 5],
        [7, 8],
        [4, 8],
        [5, 8]])]

In [16]:
np.vsplit(a2,2)    # row wise vertically 2 part me divide kar dega

[array([[2, 3, 4, 5],
        [5, 6, 7, 8]]),
 array([[1, 5, 4, 8],
        [9, 2, 5, 8]])]

In [18]:
np.hsplit(a2,np.array([2,3]))  # pahle 2 column ko horizontaly print kar diya and 2+1=3 matlab 3rd column and 4th column ko

[array([[2, 3],
        [5, 6],
        [1, 5],
        [9, 2]]),
 array([[4],
        [7],
        [4],
        [5]]),
 array([[5],
        [8],
        [8],
        [8]])]

In [2]:
import numpy as np

In [3]:
a1=np.array([[12,34,56],[67,54,12]])

In [4]:
a1

array([[12, 34, 56],
       [67, 54, 12]])

In [5]:
#argmax()
np.argmax(a1)

3

In [17]:
np.argmax(a1,axis=0)   # verticaly dekhega har ek column ko dekhega ki sabse bada element kis row me hai us row ka index index me hai

array([1, 1, 0], dtype=int64)

In [18]:
np.argmax(a1,axis=1)   # har horizontal row ko dekhega ki sabse bada  element kon se column index number me hai

array([2, 0], dtype=int64)

In [10]:
a1

array([[12, 34, 56],
       [67, 54, 12]])

In [23]:
np.argmin(a1,axis=0) # verticaly check hoga aur requirment ke anusar us row ka index likh dega

array([0, 0, 1], dtype=int64)

In [24]:
np.argmin(a1,axis=1) # horizontaly check hoga aur requirement ke sath us column ka index print hoga

array([0, 2], dtype=int64)

In [19]:
a2=np.array([1,9,3,8,5,2,7,6,4])

In [22]:
np.argsort(a2) # minimum number ko uske index me covert karke batayega

array([0, 5, 2, 8, 4, 7, 6, 3, 1], dtype=int64)

PANDAS READING

In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('covid_dataset.csv')

In [3]:
data

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  \
0           Afghanistan      36263    1269      25198    9796        106   
1               Albania       4880     144       2745    1991        117   
2               Algeria      27973    1163      18837    7973        616   
3               Andorra        907      52        803      52         10   
4                Angola        950      41        242     667         18   
..                  ...        ...     ...        ...     ...        ...   
182  West Bank and Gaza      10621      78       3752    6791        152   
183      Western Sahara         10       1          8       1          0   
184               Yemen       1691     483        833     375         10   
185              Zambia       4552     140       2815    1597         71   
186            Zimbabwe       2704      36        542    2126        192   

     New deaths  New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0            10             18                3.50                  69.49   
1             6             63                2.95                  56.25   
2             8            749                4.16                  67.34   
3             0              0                5.73                  88.53   
4             1              0                4.32                  25.47   
..          ...            ...                 ...                    ...   
182           2              0                0.73                  35.33   
183           0              0               10.00                  80.00   
184           4             36               28.56                  49.26   
185           1            465                3.08                  61.84   
186           2             24                1.33                  20.04   

     Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                      5.04                35526            737   
1                      5.25                 4171            709   
2                      6.17                23691           4282   
3                      6.48                  884             23   
4                     16.94                  749            201   
..                      ...                  ...            ...   
182                    2.08                 8916           1705   
183                   12.50                   10              0   
184                   57.98                 1619             72   
185                    4.97                 3326           1226   
186                    6.64                 1713            991   

     1 week % increase             WHO Region  
0                 2.07  Eastern Mediterranean  
1                17.00                 Europe  
2                18.07                 Africa  
3                 2.60                 Europe  
4                26.84                 Africa  
..                 ...                    ...  
182              19.12  Eastern Mediterranean  
183               0.00                 Africa  
184               4.45  Eastern Mediterranean  
185              36.86                 Africa  
186              57.85                 Africa  

[187 rows x 15 columns]

In [4]:
type(data)

pandas.core.frame.DataFrame

In [5]:
data.head(5)

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0    Afghanistan      36263    1269      25198    9796        106          10   
1        Albania       4880     144       2745    1991        117           6   
2        Algeria      27973    1163      18837    7973        616           8   
3        Andorra        907      52        803      52         10           0   
4         Angola        950      41        242     667         18           1   

   New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0             18                3.50                  69.49   
1             63                2.95                  56.25   
2            749                4.16                  67.34   
3              0                5.73                  88.53   
4              0                4.32                  25.47   

   Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                    5.04                35526            737   
1                    5.25                 4171            709   
2                    6.17                23691           4282   
3                    6.48                  884             23   
4                   16.94                  749            201   

   1 week % increase             WHO Region  
0               2.07  Eastern Mediterranean  
1              17.00                 Europe  
2              18.07                 Africa  
3               2.60                 Europe  
4              26.84                 Africa

 read pandas excel file
 
 data=pd.read_excel('iris.xlsx')

In [7]:
pd.set_option("display.max_rows",None,"display.max_columns",None)

In [8]:
data

Country/Region  Confirmed  Deaths  Recovered   Active  \
0                         Afghanistan      36263    1269      25198     9796   
1                             Albania       4880     144       2745     1991   
2                             Algeria      27973    1163      18837     7973   
3                             Andorra        907      52        803       52   
4                              Angola        950      41        242      667   
5                 Antigua and Barbuda         86       3         65       18   
6                           Argentina     167416    3059      72575    91782   
7                             Armenia      37390     711      26665    10014   
8                           Australia      15303     167       9311     5825   
9                             Austria      20558     713      18246     1599   
10                         Azerbaijan      30446     423      23242     6781   
11                            Bahamas        382      11         91      280   
12                            Bahrain      39482     141      36110     3231   
13                         Bangladesh     226225    2965     125683    97577   
14                           Barbados        110       7         94        9   
15                            Belarus      67251     538      60492     6221   
16                            Belgium      66428    9822      17452    39154   
17                             Belize         48       2         26       20   
18                              Benin       1770      35       1036      699   
19                             Bhutan         99       0         86       13   
20                            Bolivia      71181    2647      21478    47056   
21             Bosnia and Herzegovina      10498     294       4930     5274   
22                           Botswana        739       2         63      674   
23                             Brazil    2442375   87618    1846641   508116   
24                             Brunei        141       3        138        0   
25                           Bulgaria      10621     347       5585     4689   
26                       Burkina Faso       1100      53        926      121   
27                              Burma        350       6        292       52   
28                            Burundi        378       1        301       76   
29                         Cabo Verde       2328      22       1550      756   
30                           Cambodia        226       0        147       79   
31                           Cameroon      17110     391      14539     2180   
32                             Canada     116458    8944          0   107514   
33           Central African Republic       4599      59       1546     2994   
34                               Chad        922      75        810       37   
35                              Chile     347923    9187     319954    18782   
36                              China      86783    4656      78869     3258   
37                           Colombia     257101    8777     131161   117163   
38                            Comoros        354       7        328       19   
39                Congo (Brazzaville)       3200      54        829     2317   
40                   Congo (Kinshasa)       8844     208       5700     2936   
41                         Costa Rica      15841     115       3824    11902   
42                      Cote d'Ivoire      15655      96      10361     5198   
43                            Croatia       4881     139       3936      806   
44                               Cuba       2532      87       2351       94   
45                             Cyprus       1060      19        852      189   
46                            Czechia      15516     373      11428     3715   
47                            Denmark      13761     613      12605      543   
48                           Djibouti       5059      58       4977       24   
49                     

In [9]:
data.head(5)

Country/Region  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0    Afghanistan      36263    1269      25198    9796        106          10   
1        Albania       4880     144       2745    1991        117           6   
2        Algeria      27973    1163      18837    7973        616           8   
3        Andorra        907      52        803      52         10           0   
4         Angola        950      41        242     667         18           1   

   New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0             18                3.50                  69.49   
1             63                2.95                  56.25   
2            749                4.16                  67.34   
3              0                5.73                  88.53   
4              0                4.32                  25.47   

   Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                    5.04                35526            737   
1                    5.25                 4171            709   
2                    6.17                23691           4282   
3                    6.48                  884             23   
4                   16.94                  749            201   

   1 week % increase             WHO Region  
0               2.07  Eastern Mediterranean  
1              17.00                 Europe  
2              18.07                 Africa  
3               2.60                 Europe  
4              26.84                 Africa

In [10]:
dict={"roll":[1,2,3,4,5,6,7,8,9],"marks":[23,25,27,29,24,26,30,28,24]}

In [11]:
df=pd.DataFrame(dict)

In [12]:
df

roll  marks
0     1     23
1     2     25
2     3     27
3     4     29
4     5     24
5     6     26
6     7     30
7     8     28
8     9     24

In [21]:
df.to_csv('student.csv')  # create csv file

In [22]:
df.to_excel('student.xlsx',sheet_name="student_data")  # create exel file

In [25]:
country=pd.read_html('https://en.wikipedia.org/wiki/List_of_sovereign_states')  # internet connection required

In [26]:
country

[                               Common and formal names  \
 0                                                  NaN   
 1    UN member states and General Assembly observer...   
 2                      Abkhazia → See Abkhazia listing   
 3                                          Afghanistan   
 4                        Albania – Republic of Albania   
 5    Algeria – People's Democratic Republic of Algeria   
 6                    Andorra – Principality of Andorra   
 7                          Angola – Republic of Angola   
 8                                  Antigua and Barbuda   
 9                    Argentina – Argentine Republic[h]   
 10                       Armenia – Republic of Armenia   
 11                       Artsakh → See Artsakh listing   
 12               Australia – Commonwealth of Australia   
 13                       Austria – Republic of Austria   
 14                 Azerbaijan – Republic of Azerbaijan   
 15      Bahamas, The – Commonwealth of The Bahamas[15] 

In [27]:
# pandas data structure:series
# series is one dimensional array with label which can hold data of any type such as integer,string,float,python object etc
# in series,we can set own index label like 'a','b','c'.....
# passed index is the list of axis label

In [31]:
list1=[53,63,63,39,92,20]
s1=pd.Series(list1)

In [32]:
s1

0    53
1    63
2    63
3    39
4    92
5    20
dtype: int64

In [33]:
s2=pd.Series(list1,index=['a','b','c','d','e','f'])

In [34]:
s2

a    53
b    63
c    63
d    39
e    92
f    20
dtype: int64

In [35]:
s2.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [36]:
dict1={'a':300,'b':450,'c':643,'d':432}

In [43]:
s3=pd.Series(dict1)

In [44]:
s3

a    300
b    450
c    643
d    432
dtype: int64

In [46]:
s4=pd.Series(dict1,index=['a','b','c','a','d','b'])

In [47]:
s4

a    300
b    450
c    643
a    300
d    432
b    450
dtype: int64

In [49]:
s5=pd.Series(100,index=['aa','bb','cc'])

In [50]:
s5

aa    100
bb    100
cc    100
dtype: int64

In [51]:
s4

a    300
b    450
c    643
a    300
d    432
b    450
dtype: int64

In [52]:
s4.to_numpy()

array([300, 450, 643, 300, 432, 450], dtype=int64)

In [53]:
arr=s4.to_numpy()

In [54]:
arr

array([300, 450, 643, 300, 432, 450], dtype=int64)

In [55]:
s4

a    300
b    450
c    643
a    300
d    432
b    450
dtype: int64

In [56]:
s4+s4

a     600
b     900
c    1286
a     600
d     864
b     900
dtype: int64

In [58]:
s7=s4*10

In [59]:
s7

a    3000
b    4500
c    6430
a    3000
d    4320
b    4500
dtype: int64

In [80]:
# numpy ke function me series ko pas kar sakte hai

In [81]:
import numpy as np

In [82]:
Arr1=np.exp(s4)

In [83]:
Arr1

a    1.942426e+130
b    2.707178e+195
c    1.783823e+279
a    1.942426e+130
d    4.123027e+187
b    2.707178e+195
dtype: float64

In [84]:
Arr2=np.sin(s4)

In [85]:
Arr2

a   -0.999756
b   -0.683284
c    0.855489
a   -0.999756
d   -0.999519
b   -0.683284
dtype: float64

In [86]:
Arr3=np.sqrt(s4)

In [87]:
Arr3

a    17.320508
b    21.213203
c    25.357445
a    17.320508
d    20.784610
b    21.213203
dtype: float64

In [88]:
Arr4=np.max(s4)

In [89]:
Arr4

643

In [90]:
Arr5=np.log(s4)

In [91]:
Arr5

a    5.703782
b    6.109248
c    6.466145
a    5.703782
d    6.068426
b    6.109248
dtype: float64

In [92]:
Arr6=np.mean(s4)

In [93]:
Arr6

429.1666666666667

In [94]:
Arr6=np.median(s4)

In [95]:
Arr6

441.0

In [96]:
Arr7=np.std(s4)

In [97]:
Arr7

115.44755904257522

In [98]:
Arr8=np.var(s4)

In [99]:
Arr8

13328.13888888889

In [2]:
import pandas as pd

In [3]:
List2=[653,74,837]
s6=pd.Series(List2,name="simplynumber")

In [4]:
s6

0    653
1     74
2    837
Name: simplynumber, dtype: int64

In [5]:
s8=s6.rename('simplyinteger')

In [6]:
s8

0    653
1     74
2    837
Name: simplyinteger, dtype: int64

In [8]:
s8[0]

653

In [9]:
s8[:]

0    653
1     74
2    837
Name: simplyinteger, dtype: int64

In [10]:
s8[s8>50]

0    653
1     74
2    837
Name: simplyinteger, dtype: int64

In [11]:
s8[s8>s8.mean()]

0    653
2    837
Name: simplyinteger, dtype: int64

In [12]:
s8

0    653
1     74
2    837
Name: simplyinteger, dtype: int64

In [15]:
s8[2]=100  #value change

In [16]:
s8

0    653
1     74
2    100
Name: simplyinteger, dtype: int64

In [23]:
List=[1,2,3,6,3,9]
s9=pd.Series(List,index=['a','b','c','d','e','f'])

In [24]:
s9

a    1
b    2
c    3
d    6
e    3
f    9
dtype: int64

In [25]:
s9['d']

6

In [28]:
df=pd.DataFrame(List)

In [29]:
df.to_csv('List.csv')

PANDAS DATA STRUCTURE:DataFrame

dataframe is a 2 dimensional labelled(row and column) datastructure like an array with possibility of different datatype columns.

it is a table in sql , spreadsheet etc

dataframe can be created using dictionary, two dimensional array of numpy, series and another dataframe

In [17]:
import numpy as np 

In [18]:
import pandas as pd

In [19]:
dict1={'roll':[1,2,3,4,5,6,7],'marks':[32,54,43,60,56,46,65]}

In [20]:
df1=pd.DataFrame(dict1,index=[0,1,2,3,4,5,6])

In [21]:
df1

roll  marks
0     1     32
1     2     54
2     3     43
3     4     60
4     5     56
5     6     46
6     7     65

In [22]:
df2=pd.DataFrame(dict1,index=['a','b','c','d','e','f','g'])

In [23]:
df2

roll  marks
a     1     32
b     2     54
c     3     43
d     4     60
e     5     56
f     6     46
g     7     65

In [24]:
df3=pd.DataFrame(dict1,index=['a','b','c','d','e','f','g'],columns=['marks','roll'])

In [25]:
df3

marks  roll
a     32     1
b     54     2
c     43     3
d     60     4
e     56     5
f     46     6
g     65     7

In [26]:
df1.index

Int64Index([0, 1, 2, 3, 4, 5, 6], dtype='int64')

In [27]:
df2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g'], dtype='object')

In [28]:
df1.columns

Index(['roll', 'marks'], dtype='object')

In [29]:
df2.columns

Index(['roll', 'marks'], dtype='object')

In [30]:
Head=[('Roll',"i4"),("marks","f4"),("name","S20")]
Value=[(1,90,'Rahul'),(2,89,'Rakesh'),(3,65,'Roushan')]
Data=np.array(Value,dtype=Head)
Data

array([(1, 90., b'Rahul'), (2, 89., b'Rakesh'), (3, 65., b'Roushan')],
      dtype=[('Roll', '<i4'), ('marks', '<f4'), ('name', 'S20')])

In [31]:
Marks_Data=pd.DataFrame(Data)

In [32]:
Marks_Data

Roll  marks        name
0     1   90.0    b'Rahul'
1     2   89.0   b'Rakesh'
2     3   65.0  b'Roushan'

In [33]:
Student=[{"roll":1,"Name":"rakesh"},{"roll":2,"Name":"roshan"}]
Student_Data=pd.DataFrame(Student)

In [34]:
Student_Data

roll    Name
0     1  rakesh
1     2  roshan

namedtuple()


In [35]:
from collections import namedtuple

In [36]:
import pandas as pd

In [37]:
Axis=namedtuple("Axis","a b")

In [38]:
Axis_data=pd.DataFrame([Axis(9,10),Axis(1,0),Axis(0,0)])

In [39]:
Axis_data

a   b
0  9  10
1  1   0
2  0   0

In [40]:
Axis=namedtuple("Axis","a b c d")

In [41]:
Axis_data=pd.DataFrame([Axis(9,10,6,8),Axis(1,0,7,5),Axis(0,0,9,1)])

In [42]:
Axis_data

a   b  c  d
0  9  10  6  8
1  1   0  7  5
2  0   0  9  1

In [43]:
Marks_Data

Roll  marks        name
0     1   90.0    b'Rahul'
1     2   89.0   b'Rakesh'
2     3   65.0  b'Roushan'

from_records ka use karke roll,markes,names me se kisi ko bhi index bana sakte hai

In [44]:
data1=pd.DataFrame.from_records(Data,index='Roll')

In [45]:
data1

marks        name
Roll                   
1      90.0    b'Rahul'
2      89.0   b'Rakesh'
3      65.0  b'Roushan'

In [47]:
Marks_Data

Roll  marks        name
0     1   90.0    b'Rahul'
1     2   89.0   b'Rakesh'
2     3   65.0  b'Roushan'

new column ko add karna hai

In [48]:
Marks_Data['subjects']=[3,4,2]

In [49]:
Marks_Data

Roll  marks        name  subjects
0     1   90.0    b'Rahul'         3
1     2   89.0   b'Rakesh'         4
2     3   65.0  b'Roushan'         2

In [51]:
Marks_Data["Total_Marks"]=Marks_Data['marks']*Marks_Data['subjects']

In [52]:
Marks_Data

Roll  marks        name  subjects  Total_Marks
0     1   90.0    b'Rahul'         3        270.0
1     2   89.0   b'Rakesh'         4        356.0
2     3   65.0  b'Roushan'         2        130.0

In [61]:
Marks_Data['results']=Marks_Data['Total_Marks']>200

In [62]:
Marks_Data

Roll  marks        name     city  subjects  Total_Marks  results
0     1   90.0    b'Rahul'    delhi         3        270.0     True
1     2   89.0   b'Rakesh'  kolkata         4        356.0     True
2     3   65.0  b'Roushan'   mumbai         2        130.0    False

hame third index me ek new columns insert karna hai 

In [64]:
Marks_Data.insert(3,"City",["delhi","kolkata","mumbai"])

In [65]:
Marks_Data

Roll  marks        name     City     city  subjects  Total_Marks  results
0     1   90.0    b'Rahul'    delhi    delhi         3        270.0     True
1     2   89.0   b'Rakesh'  kolkata  kolkata         4        356.0     True
2     3   65.0  b'Roushan'   mumbai   mumbai         2        130.0    False

transpose of data frame

rows ko column me convert karna hai and columns ko row me

In [66]:
Marks_Data.T

0          1           2
Roll                1          2           3
marks            90.0       89.0        65.0
name         b'Rahul'  b'Rakesh'  b'Roushan'
City            delhi    kolkata      mumbai
city            delhi    kolkata      mumbai
subjects            3          4           2
Total_Marks     270.0      356.0       130.0
results          True       True       False

In [67]:
Marks_Data

Roll  marks        name     City     city  subjects  Total_Marks  results
0     1   90.0    b'Rahul'    delhi    delhi         3        270.0     True
1     2   89.0   b'Rakesh'  kolkata  kolkata         4        356.0     True
2     3   65.0  b'Roushan'   mumbai   mumbai         2        130.0    False

first row se lekar and second column se lekar last tak ka dataframe dekhna hai 

In [69]:
Marks_Data.iloc[1:,2:]

name     City     city  subjects  Total_Marks  results
1   b'Rakesh'  kolkata  kolkata         4        356.0     True
2  b'Roushan'   mumbai   mumbai         2        130.0    False

hame dataframe ka sabhi rows and column me 2 se 5 index tak ka column chahiye

In [70]:
Marks_Data.iloc[:,2:5]

name     City     city
0    b'Rahul'    delhi    delhi
1   b'Rakesh'  kolkata  kolkata
2  b'Roushan'   mumbai   mumbai

merging joining and concatening